"""initial migration

Revision ID: 47a1cd80b4c2
Revises: 
Create Date: 2017-02-08 18:26:54.371000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a1cd80b4c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comicinfo',
    sa.Column('comicid', sa.String(length=15), nullable=False),
    sa.Column('packageid', sa.String(length=15), nullable=True),
    sa.Column('comicname', sa.String(length=50), nullable=True),
    sa.Column('brief', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=1), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('curchapter', sa.Integer(), nullable=True),
    sa.Column('freechapter', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('recentupdatetime', sa.DateTime(), nullable=True),
    sa.Column('modifiedtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('comicid')
    )
    op.create_table('packageinfo',
    sa.Column('packageid', sa.String(length=255), nullable=False),
    sa.Column('packagename', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('modifiedtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('packageid')
    )
    op.create_table('userinfo',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('phonenum', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('integral', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    op.drop_table('packageinfo')
    op.drop_table('comicinfo')
    # ### end Alembic commands ###
